version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: production
    env_file: .env.docker ## Using custom environment file
    volumes:
      - storage_data:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'  # Expose port 3000 for local access
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5432:5432'  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chatwoot_postgres_secure_password_2024

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    environment:
      - REDIS_PASSWORD=chatwoot_redis_secure_password_2024
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'  # Expose Redis port

volumes:
  storage_data:
  postgres_data:
  redis_data: 